const CONTENTS = [
    {
        type: "nav",
        parentId: "upperNav",
        itemId: "",
        itemClass: "",
        itemTitle: "Our Story",
        itemLink: "https://medium.com/about?autoplay=1",
        itemLinkClass: "",
        itemLinkId: "",
        order: 1
    },
    {
        type: "nav",
        parentId: "upperNav",
        itemId: "",
        itemClass: "",
        itemTitle: "Membership",
        itemLink: "https://medium.com/membership",
        itemLinkClass: "",
        itemLinkId: "",
        order: 2
    },
    {
        type: "nav",
        parentId: "upperNav",
        itemId: "",
        itemClass: "",
        itemTitle: "Write",
        itemLink: "https://medium.com/m/signin?operation=register&redirect=https%3A%2F%2Fmedium.com%2Fnew-story&source=--------------------------new_post_topnav-----------",
        itemLinkClass: "",
        itemLinkId: "",
        order: 3
    },
    {
        type: "nav",
        parentId: "upperNav",
        itemId: "",
        itemClass: "",
        itemTitle: "Sign In",
        itemLink: "https://medium.com/m/signin?operation=login&redirect=https%3A%2F%2Fmedium.com%2F&source=--------------------------lo_home_nav-----------",
        itemLinkClass: "",
        itemLinkId: "",
        order: 4
    },
    {
        type: "nav",
        parentId: "upperNav",
        itemId: "getStarted",
        itemClass: "changeBgOnScroll",
        itemTitle: "Get Started",
        itemLink: "https://medium.com/m/signin?operation=register&redirect=https%3A%2F%2Fmedium.com%2F&source=--------------------------lo_home_nav-----------",
        itemLinkClass: "changeColorOnScroll",
        itemLinkId: "",
        order: 5
    },
    {
        type: "nav",
        parentId: "argumentsCloud",
        itemId: "",
        itemClass: "navItem",
        itemTitle: "Programming",
        itemLink: "https://medium.com/tag/programming",
        itemLinkClass: "navItemLink",
        itemLinkId: "",
        order: 1
    },
    {
        type: "nav",
        parentId: "argumentsCloud",
        itemId: "",
        itemClass: "navItem",
        itemTitle: "Data Science",
        itemLink: "https://medium.com/tag/data-science",
        itemLinkClass: "navItemLink",
        itemLinkId: "",
        order: 2
    },
    {
        type: "nav",
        parentId: "argumentsCloud",
        itemId: "",
        itemClass: "navItem",
        itemTitle: "technology",
        itemLink: "https://medium.com/tag/technology",
        itemLinkClass: "navItemLink",
        itemLinkId: "",
        order: 3
    },
    {
        type: "nav",
        parentId: "argumentsCloud",
        itemId: "",
        itemClass: "navItem",
        itemTitle: "Self Improvement",
        itemLink: "https://medium.com/tag/self-improvement",
        itemLinkClass: "navItemLink",
        itemLinkId: "",
        order: 4
    },
    {
        type: "nav",
        parentId: "argumentsCloud",
        itemId: "",
        itemClass: "navItem",
        itemTitle: "Writing",
        itemLink: "https://medium.com/tag/writing",
        itemLinkClass: "navItemLink",
        itemLinkId: "",
        order: 5
    },
    {
        type: "nav",
        parentId: "argumentsCloud",
        itemId: "",
        itemClass: "navItem",
        itemTitle: "Relationships",
        itemLink: "https://medium.com/tag/relationships",
        itemLinkClass: "navItemLink",
        itemLinkId: "",
        order: 6
    },
    {
        type: "nav",
        parentId: "argumentsCloud",
        itemId: "",
        itemClass: "navItem",
        itemTitle: "Machine Learning",
        itemLink: "https://medium.com/tag/machine-learning",
        itemLinkClass: "navItemLink",
        itemLinkId: "",
        order: 7
    },
    {
        type: "nav",
        parentId: "argumentsCloud",
        itemId: "",
        itemClass: "navItem",
        itemTitle: "Productivity",
        itemLink: "https://medium.com/tag/productivity",
        itemLinkClass: "navItemLink",
        itemLinkId: "",
        order: 8
    },
    {
        type: "nav",
        parentId: "argumentsCloud",
        itemId: "",
        itemClass: "navItem",
        itemTitle: "Politics",
        itemLink: "https://medium.com/tag/politics",
        itemLinkClass: "navItemLink",
        itemLinkId: "",
        order: 9
    },
    {
        type: "nav",
        parentId: "lastNav",
        itemId: "",
        itemClass: "navItem",
        itemTitle: "Help",
        itemLink: "https://help.medium.com/hc/en-us",
        itemLinkClass: "navItemLink",
        itemLinkId: "",
        order: 1
    },
    {
        type: "nav",
        parentId: "lastNav",
        itemId: "",
        itemClass: "navItem",
        itemTitle: "Status",
        itemLink: "https://medium.statuspage.io/",
        itemLinkClass: "navItemLink",
        itemLinkId: "",
        order: 2
    },
    {
        type: "nav",
        parentId: "lastNav",
        itemId: "",
        itemClass: "navItem",
        itemTitle: "Writers",
        itemLink: "https://medium.com/m/signin?operation=register&redirect=https%3A%2F%2Fmedium.com%2Fnew-story&source=--------------------------new_post_topnav-----------",
        itemLinkClass: "navItemLink",
        itemLinkId: "",
        order: 3
    },
    {
        type: "nav",
        parentId: "lastNav",
        itemId: "",
        itemClass: "navItem",
        itemTitle: "Blog",
        itemLink: "https://blog.medium.com/",
        itemLinkClass: "navItemLink",
        itemLinkId: "",
        order: 4
    },
    {
        type: "nav",
        parentId: "lastNav",
        itemId: "",
        itemClass: "navItem",
        itemTitle: "Careers",
        itemLink: "https://medium.com/jobs-at-medium/work-at-medium-959d1a85284e",
        itemLinkClass: "navItemLink",
        itemLinkId: "",
        order: 5
    },
    {
        type: "nav",
        parentId: "lastNav",
        itemId: "",
        itemClass: "navItem",
        itemTitle: "Privacy",
        itemLink: "https://policy.medium.com/medium-privacy-policy-f03bf92035c9",
        itemLinkClass: "navItemLink",
        itemLinkId: "",
        order: 6
    },
    {
        type: "nav",
        parentId: "lastNav",
        itemId: "",
        itemClass: "navItem",
        itemTitle: "Terms",
        itemLink: "https://policy.medium.com/medium-terms-of-service-9db0094a1e0f",
        itemLinkClass: "navItemLink",
        itemLinkId: "",
        order: 7
    },
    {
        type: "nav",
        parentId: "lastNav",
        itemId: "",
        itemClass: "navItem",
        itemTitle: "About",
        itemLink: "https://medium.com/about?autoplay=1",
        itemLinkClass: "navItemLink",
        itemLinkId: "",
        order: 7
    },
    {
        type: "nav",
        parentId: "lastNav",
        itemId: "",
        itemClass: "navItem",
        itemTitle: "Knowable",
        itemLink: "https://medium.com/business",
        itemLinkClass: "navItemLink",
        itemLinkId: "",
        order: 8
    },
    {
        author: "Tom Cooper",
        authorImgSrc: "/assets/imgs/image01.jpeg",
        authorImgShape: "rounded",
        authorLink: "",
        title: "Ukraine War, 23 October 2022",
        date: "Oct 23",
        readTime: "5 min",
        imgSrc: "/assets/imgs/image01.jpeg",
        excerpt: "",
        category: "",
        inPublication: "",
        star: false,
        titleLink: "",
        type: "article",
        order: 1,
        parentId: "trendingNewsCards"
    },
    {
        author: "Arthur Hayes",
        authorImgSrc: "/assets/imgs/image02.png",
        authorImgShape: "rounded",
        authorLink: "",
        title: "Comeback",
        date: "Oct 26",
        readTime: "24 min",
        imgSrc: "/assets/imgs/image02.png",
        excerpt: "",
        category: "",
        inPublication: "Entrepreneur's Handbook",
        titleLink: "",
        star: false,
        type: "article",
        order: 2,
        parentId: "trendingNewsCards"
    },
    {
        author: "Erin A Ross",
        authorImgSrc: "/assets/imgs/image03.jpeg",
        authorImgShape: "squared",
        authorLink: "",
        title: "How I Learned to Love My Breasts Even Though One Is A Horcrux For Voldemort",
        date: "Oct 26",
        readTime: "2 min",
        imgSrc: "/assets/imgs/image03.jpeg",
        excerpt: "",
        category: "",
        inPublication: "Slackjaw",
        titleLink: "",

        star: false,
        type: "article",
        order: 3,
        parentId: "trendingNewsCards"
    },
    {
        author: "Frank Mastropolo",
        authorImgSrc: "/assets/imgs/image04.png",
        authorImgShape: "squared",
        authorLink: "",
        title: "The Night Paul McCartney Donned a Disguise at Fillmore East",
        date: "Oct 22",
        readTime: "3 min",
        imgSrc: "/assets/imgs/image04.png",
        excerpt: "",
        category: "",
        inPublication: "The Riff",
        titleLink: "",
        star: true,
        type: "article",
        order: 4,
        parentId: "trendingNewsCards"
    },
    {
        author: "Frank Andrade",
        authorImgSrc: "/assets/imgs/image05.jpeg",
        authorImgShape: "squared",
        authorLink: "",
        title: "5 Python Projects to Automate Your Life: From Beginner to Advanced",
        date: "Oct 13",
        readTime: "6 min",
        imgSrc: "/assets/imgs/image05.jpeg",
        excerpt: "",
        category: "",
        inPublication: "Towards Data Science",
        titleLink: "",
        star: true,
        type: "article",
        order: 5,
        parentId: "trendingNewsCards"
    },
    {
        author: "Wesley Smits",
        authorImgSrc: "/assets/imgs/image06.png",
        authorImgShape: "squared",
        authorLink: "",
        title: "How To Make Visual Studio Code Look Amazing",
        date: "Oct 20",
        readTime: "7 min",
        imgSrc: "/assets/imgs/image06.png",
        excerpt: "",
        category: "",
        inPublication: "JavaScript in Plain English",
        titleLink: "",
        star: true,
        type: "article",
        order: 6,
        parentId: "trendingNewsCards"
    },
    {
        author: "Robert Roy Britt",
        authorImgSrc: "/assets/imgs/image07.jpeg",
        authorImgShape: "rounded",
        authorLink: "",
        title: "How Old is Old?",
        excerpt: "What we consider \u201cold\u201d changes dramatically with age, and our perspectives can be predictive of how well we age",
        date: "Oct 27",
        readTime: "5 min",
        category: "Aging",
        imgSrc: "/assets/imgs/image08.jpeg",
        inPublication: "",
        titleLink: "",
        star: true,
        type: "article",
        order: 1,
        parentId: "firstColumn"
    },
    {
        author: "Taru Anniina Liikanen",
        authorImgSrc: "/assets/imgs/image09.jpeg",
        authorImgShape: "rounded",
        authorLink: "",
        title: "Is Taylor Swift Allowed to Speak About Fat?",
        excerpt: "Can you speak about your trauma if you don't look traumatized?",
        date: "Oct 24",
        readTime: "6 min",
        category: "Health",
        imgSrc: "/assets/imgs/image10.jpeg",
        inPublication: "",
        titleLink: "",
        star: true,
        type: "article",
        order: 2,
        parentId: "firstColumn"
    },
    {
        author: "David Rodenas, Ph. D.",
        authorImgSrc: "/assets/imgs/image11.jpeg",
        authorImgShape: "rounded",
        authorLink: "",
        title: "Don't Screw Up, You Will Be Found Guilty",
        excerpt: "Software Engineer, yours is the right to produce high-quality work at all times, also the liability.",
        date: "Oct 15",
        readTime: "5 min",
        category: "Software Engineering",
        imgSrc: "/assets/imgs/image12.png",
        inPublication: "",
        titleLink: "",
        star: true,
        type: "article",
        order: 3,
        parentId: "firstColumn"
    },
    {
        author: "Microsoft Design",
        authorImgSrc: "/assets/imgs/image13.png",
        authorImgShape: "rounded",
        authorLink: "",
        title: "Leave No Trace",
        excerpt: "How product designers can break from the status quo and help our planet",
        date: "Oct 26",
        readTime: "7 min",
        category: "Sustainability",
        imgSrc: "/assets/imgs/image14.png",
        inPublication: "",
        titleLink: "",

        star: false,
        type: "article",
        order: 4,
        parentId: "firstColumn"
    },
    {
        author: "Scott H. Young",
        authorImgSrc: "/assets/imgs/image15.jpeg",
        authorImgShape: "rounded",
        authorLink: "",
        title: "Variability, Not Repetition, is the Key to Mastery",
        excerpt: "Bruce Lee is reported to have said, \u201cI fear not the man who has practiced 10,000 kicks once, but the man who has practiced one kick 10,000...",
        date: "Oct 26",
        readTime: "7 min",
        category: "Health",
        imgSrc: "/assets/imgs/image16.jpg",
        inPublication: "",
        titleLink: "",
        star: true,
        type: "article",
        order: 5,
        parentId: "firstColumn"
    },
    {
        author: "Paul A. DeStefanoin",
        authorImgSrc: "/assets/imgs/image17.png",
        authorImgShape: "rounded",
        authorLink: "",
        title: "What I Overheard as an Escape Room Actor",
        excerpt: "Lock a group of people in a room and you\u2019ll witness some surprising confessions",
        date: "Jan 18, 2020",
        readTime: "6 min",
        category: "Experiences",
        imgSrc: "/assets/imgs/image18.jpeg",
        inPublication: "",
        titleLink: "",
        star: true,
        type: "article",
        order: 6,
        parentId: "firstColumn"
    },
    {
        author: "Kim Scott",
        authorImgSrc: "/assets/imgs/image19.jpeg",
        authorImgShape: "rounded",
        authorLink: "",
        title: "6 Steps for Setting Measurable Goals to Avoid \u201cProductivity Paranoia\u201d",
        excerpt: "With more people working in remote and hybrid environments than ever before, company, team and individual goals must be explicit and...",
        date: "Oct 24",
        readTime: "6 min",
        category: "Health",
        imgSrc: "/assets/imgs/image20.jpg",
        inPublication: "",
        titleLink: "",

        star: false,
        type: "article",
        order: 7,
        parentId: "firstColumn"
    }
];
